import { FormEvent, useEffect, useState } from "react";

type Code = { id: number; code: string; durationDays: number; status: string; createdAt: string; activatedAt?: string; expiresAt?: string; terminatedAt?: string; lastSeenAt?: string; useCount: number };
const labels: Record<string,string> = { unused: "未使用", active: "使用中", expired: "已到期", terminated: "已终止" };
function time(v?: string) { return v ? new Date(v).toLocaleString("zh-CN", { hour12: false }) : "—"; }

export default function AdminAccess() {
  const [auth, setAuth] = useState<boolean | null>(null); const [codes, setCodes] = useState<Code[]>([]); const [filter, setFilter] = useState({ days: "", status: "", q: "" }); const [login, setLogin] = useState({ username: "", password: "" }); const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/status").then(async r=>{ const text=await r.text(); if(!r.ok) throw new Error(`状态接口 ${r.status}`); let j: {authenticated?: boolean}; try { j=JSON.parse(text); } catch { throw new Error("后端尚未更新，请重启服务"); } setAuth(Boolean(j.authenticated)); if(j.authenticated) return fetch(`/api/admin/access-codes?days=${filter.days}&status=${filter.status}&q=${encodeURIComponent(filter.q)}`).then(r=>r.json()).then(j=>setCodes(j.codes||[])); }).catch(e=>{ setAuth(false); setMessage(e instanceof Error ? e.message : "无法连接后端"); });
  useEffect(()=>{load()},[]); useEffect(()=>{if(auth)load()},[filter.days,filter.status,filter.q]);
  async function submit(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)});if(!r.ok){setMessage("账号或密码错误");return}setAuth(true);setLogin({username:"",password:""});}
  async function terminate(id:number){if(!confirm("确定终止此访问码？已有会话将立即失效。"))return;await fetch(`/api/admin/access-codes/${id}/terminate`,{method:"POST"});load()}
  async function generate(days:number){await fetch("/api/admin/access-codes/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({durationDays:days,count:1000})});setMessage(`已确保 ${days} 天访问码池不少于 1000 份`);load()}
  if(auth===null)return <div className="admin-shell">正在验证管理员会话…</div>;
  if(!auth)return <main className="admin-shell"><form className="admin-login" onSubmit={submit}><p className="eyebrow">PRIVATE CONSOLE</p><h1>管理员登录</h1><p>请输入管理员账号和密码。</p><input placeholder="管理员账号" value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><input type="password" placeholder="管理员密码" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="btn primary">登录</button>{message&&<div className="access-error">{message}</div>}</form></main>;
  return <main className="admin-shell"><header className="admin-head"><div><p className="eyebrow">PRIVATE CONSOLE</p><h1>访问码管理</h1></div><button className="btn" onClick={()=>{fetch("/api/admin/logout",{method:"POST"});setAuth(false)}}>退出</button></header><div className="admin-toolbar"><select value={filter.days} onChange={e=>setFilter({...filter,days:e.target.value})}><option value="">全部周期</option><option value="3">3 天</option><option value="7">7 天</option><option value="15">15 天</option><option value="30">30 天</option></select><select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">全部状态</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input placeholder="搜索访问码" value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})}/>{[3,7,15,30].map(d=><button className="btn" key={d} onClick={()=>generate(d)}>补充 {d} 天</button>)}</div>{message&&<p className="admin-message">{message}</p>}<div className="admin-table-wrap"><table><thead><tr><th>访问码</th><th>周期</th><th>状态</th><th>首次使用</th><th>到期时间</th><th>最近访问</th><th>操作</th></tr></thead><tbody>{codes.map(c=><tr key={c.id}><td><code>{c.code}</code></td><td>{c.durationDays} 天</td><td><span className={`admin-status ${c.status}`}>{labels[c.status]||c.status}</span></td><td>{time(c.activatedAt)}</td><td>{time(c.expiresAt)}</td><td>{time(c.lastSeenAt)}</td><td>{c.status==="active"&&<button className="link-danger" onClick={()=>terminate(c.id)}>终止</button>}</td></tr>)}</tbody></table></div></main>;
}
